package model

import (
	"time"
)

// TODO: Add 13 more categories + own ID

// Food struct represents the food table in the database
type Food struct {
	ID                     int     `json:"id"`
	CreatedAt    		   time.Time `json:"created_at"`
	UpdatedAt    		   time.Time `json:"updated_at"`
    Name                   string  `json:"name"`
    RetentionCategory      string  `json:"retention_category"`
    GeneralCategory        string  `json:"general_category"`
    IndexCategory          string  `json:"index_category"`
    Kilocalories           float32 `json:"kilocalories"`
    Kilojoules             float32 `json:"kilojoules"`
    Water                  float32 `json:"water"`
    Protein                float32 `json:"protein"`
    Fat                    float32 `json:"fat"`
    Carbohydrates          float32 `json:"carbohydrates"`
    DietaryFiber           float32 `json:"dietary_fiber"`
    Minerals               float32 `json:"minerals"`
    OrganicAcids           float32 `json:"organic_acids"`
    Alcohol                float32 `json:"alcohol"`
    RetinolActivityEquivalent float32 `json:"retinol_activity_equivalent"`
    RetinolEquivalent      float32 `json:"retinol_equivalent"`
    Retinol                float32 `json:"retinol"`
    BetaCaroteneEquivalent float32 `json:"beta_carotene_equivalent"`
    BetaCarotene           float32 `json:"beta_carotene"`
    Calciferols            float32 `json:"calciferols"`
    AlphaTocopherolEquivalent float32 `json:"alpha_tocopherol_equivalent"`
    AlphaTocopherol        float32 `json:"alpha_tocopherol"`
    Phylloquinone          float32 `json:"phylloquinone"`
    Thiamine               float32 `json:"thiamine"`
    Riboflavin             float32 `json:"riboflavin"`
    Niacin                 float32 `json:"niacin"`
    NiacinEquivalent       float32 `json:"niacin_equivalent"`
    PantothenicAcid        float32 `json:"pantothenic_acid"`
    Pyridoxine             float32 `json:"pyridoxine"`
    Biotin                 float32 `json:"biotin"`
    FolicAcid              float32 `json:"folic_acid"`
    Cobalamin              float32 `json:"cobalamin"`
    AscorbicAcid           float32 `json:"ascorbic_acid"`
    Sodium                 float32 `json:"sodium"`
    Potassium              float32 `json:"potassium"`
    Calcium                float32 `json:"calcium"`
    Magnesium              float32 `json:"magnesium"`
    Phosphorus             float32 `json:"phosphorus"`
    Sulfur                 float32 `json:"sulfur"`
    Chloride               float32 `json:"chloride"`
    Iron                   float32 `json:"iron"`
    Zinc                   float32 `json:"zinc"`
    Copper                 float32 `json:"copper"`
    Manganese              float32 `json:"manganese"`
    Fluoride               float32 `json:"fluoride"`
    Iodide                 float32 `json:"iodide"`
    Selenium               float32 `json:"selenium"`
    Mannitol               float32 `json:"mannitol"`
    Sorbitol               float32 `json:"sorbitol"`
    Xylitol                float32 `json:"xylitol"`
    SugarAlcohols          float32 `json:"sugar_alcohols"`
    Glucose                float32 `json:"glucose"`
    Fructose               float32 `json:"fructose"`
    Galactose              float32 `json:"galactose"`
    Monosaccharides        float32 `json:"monosaccharides"`
    Sucrose                float32 `json:"sucrose"`
    Maltose                float32 `json:"maltose"`
    Lactose                float32 `json:"lactose"`
    Disaccharides          float32 `json:"disaccharides"`
    TotalSugar             float32 `json:"total_sugar"`
    ResorbableOligosaccharides float32 `json:"resorbable_oligosaccharides"`
    NonResorbableOligosaccharides float32 `json:"non_resorbable_oligosaccharides"`
    Glycogen               float32 `json:"glycogen"`
    Starch                 float32 `json:"starch"`
    Polysaccharides        float32 `json:"polysaccharides"`
    Polypentoses           float32 `json:"polypentoses"`
    Polyhexoses            float32 `json:"polyhexoses"`
    PolyuronicAcid         float32 `json:"polyuronic_acid"`
    Cellulose              float32 `json:"cellulose"`
    Lignin                 float32 `json:"lignin"`
    WaterSolubleDietaryFiber float32 `json:"water_soluble_dietary_fiber"`
    WaterInsolubleDietaryFiber float32 `json:"water_insoluble_dietary_fiber"`
    Isoleucine             float32 `json:"isoleucine"`
    Leucine                float32 `json:"leucine"`
    Lysine                 float32 `json:"lysine"`
    Methionine             float32 `json:"methionine"`
    Cysteine               float32 `json:"cysteine"`
    Phenylalanine          float32 `json:"phenylalanine"`
    Tyrosine               float32 `json:"tyrosine"`
    Threonine              float32 `json:"threonine"`
    Tryptophan             float32 `json:"tryptophan"`
    Valine                 float32 `json:"valine"`
    Arginine               float32 `json:"arginine"`
    Histidine              float32 `json:"histidine"`
    EssentialAminoAcids    float32 `json:"essential_amino_acids"`
    Alanine                float32 `json:"alanine"`
    AsparticAcid           float32 `json:"aspartic_acid"`
    GlutamicAcid           float32 `json:"glutamic_acid"`
    Glycine                float32 `json:"glycine"`
    Proline                float32 `json:"proline"`
    Serine                 float32 `json:"serine"`
    NonEssentialAminoAcids float32 `json:"non_essential_amino_acids"`
    UricAcid               float32 `json:"uric_acid"`
    Purine                 float32 `json:"purine"`
    ButyricAcid            float32 `json:"butyric_acid"`
    HexanoicAcid           float32 `json:"hexanoic_acid"`
    OctanoicAcid           float32 `json:"octanoic_acid"`
    DecanoicAcid           float32 `json:"decanoic_acid"`
    DodecanoicAcid         float32 `json:"dodecanoic_acid"`
    TetradecanoicAcid      float32 `json:"tetradecanoic_acid"`
    PentadecanoicAcid      float32 `json:"pentadecanoic_acid"`
    HexadecanoicAcid       float32 `json:"hexadecanoic_acid"`
    HeptadecanoicAcid      float32 `json:"heptadecanoic_acid"`
    OctadecanoicAcid       float32 `json:"octadecanoic_acid"`
    EicosanoicAcid         float32 `json:"eicosanoic_acid"`
    DecosanoicAcid         float32 `json:"decosanoic_acid"`
    TetracosanoicAcid      float32 `json:"tetracosanoic_acid"`
    SaturatedFattyAcids    float32 `json:"saturated_fatty_acids"`
    TetradecenoicAcid      float32 `json:"tetradecenoic_acid"`
    PentadecenoicAcid      float32 `json:"pentadecenoic_acid"`
    HexadecenoicAcid       float32 `json:"hexadecenoic_acid"`
    HeptadecenoicAcid      float32 `json:"heptadecenoic_acid"`
    OctadecenoicAcid       float32 `json:"octadecenoic_acid"`
    EicosenoicAcid         float32 `json:"eicosenoic_acid"`
    DecosenoicAcid         float32 `json:"decosenoic_acid"`
    TetracosenoicAcid      float32 `json:"tetracosenoic_acid"`
    MonounsaturatedFattyAcids float32 `json:"monounsaturated_fatty_acids"`
    HexadecadienoicAcid    float32 `json:"hexadecadienoic_acid"`
    HexadecatetraenoicAcid float32 `json:"hexadecatetraenoic_acid"`
    OctadecadienoicAcid    float32 `json:"octadecadienoic_acid"`
    OctadecatrienoicAcid   float32 `json:"octadecatrienoic_acid"`
    OctadecatetraenoicAcid float32 `json:"octadecatetraenoic_acid"`
    NonadecatrienoicAcid   float32 `json:"nonadecatrienoic_acid"`
    EicosadienoicAcid      float32 `json:"eicosadienoic_acid"`
    EicosatrienoicAcid     float32 `json:"eicosatrienoic_acid"`
    EicosatetraenoicAcid   float32 `json:"eicosatetraenoic_acid"`
    EicosapentaenoicAcid   float32 `json:"eicosapentaenoic_acid"`
    DocosadienoicAcid      float32 `json:"docosadienoic_acid"`
    DocosatrienoicAcid     float32 `json:"docosatrienoic_acid"`
    DocosatetraenoicAcid   float32 `json:"docosatetraenoic_acid"`
    DocosapentaenoicAcid   float32 `json:"docosapentaenoic_acid"`
    DocosahexaenoicAcid    float32 `json:"docosahexaenoic_acid"`
    PolyunsaturatedFattyAcids float32 `json:"polyunsaturated_fatty_acids"`
    ShortChainFattyAcids   float32 `json:"short_chain_fatty_acids"`
    MediumChainFattyAcids  float32 `json:"medium_chain_fatty_acids"`
    LongChainFattyAcids    float32 `json:"long_chain_fatty_acids"`
    Omega3FattyAcids       float32 `json:"omega_3_fatty_acids"`
    Omega6FattyAcids       float32 `json:"omega_6_fatty_acids"`
    GlycerolAndLipids      float32 `json:"glycerol_and_lipids"`
    Cholesterol            float32 `json:"cholesterol"`
    Salt                   float32 `json:"salt"`
}
