version: '3.8'

services:
  postgres_db:
    image: postgres:16.2-alpine
    restart: no
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres 
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: unrealwombat/cycling-coach-lab:latest
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      PORT: 8080
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: postgres 
      DB_PASSWORD: postgres 
      DB_NAME: postgres 
    ports:
      - 8080:8080

volumes:
  pg_data:
    external: false
