version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    restart: no
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - '5432'

volumes:
  pg_data:
    external: false
