name: Generate environment
inputs:
  base_url:
    required: true
outputs:
  commit_hash: 
    value: ${{ steps.generate_environment.outputs.commit_hash }}
  tag: 
    value: ${{ steps.generate_environment.outputs.tag }}
  url: 
    value: ${{ steps.generate_environment.outputs.url }}
runs:
  using: 'composite'
  steps:
    - id: generate_environment
      shell: bash
      run: |
        commit_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo "commit_hash: "${commit_hash}
        echo "commit_hash=$commit_hash" >> $GITHUB_OUTPUT
        tag=dev-$(echo "${{ github.head_ref }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/-/g')
        echo "tag: "${tag}
        echo "tag=$tag" >> $GITHUB_OUTPUT
        url=https://${tag}.${{ inputs.base_url }}
        echo "url: "${url}
        echo "url=$url" >> $GITHUB_OUTPUT
