name: Build and push docker image
inputs:
  docker_user:
    required: true
  docker_token:
    required: true
  tag:
    required: true
  isLatest:
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_user }}
        password: ${{ inputs.docker_token }}
    - name: Build and release docker image
      if: ${{ inputs.isLatest == 'false' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.docker_user }}/cycling-coach-lab:${{ inputs.tag }}
    - name: Build and release docker image
      if: ${{ inputs.isLatest == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.docker_user }}/cycling-coach-lab:${{ inputs.tag }}
          ${{ inputs.docker_user }}/cycling-coach-lab:latest
