// Code generated by MockGen. DO NOT EDIT.
// Source: db/db.go
//
// Generated by this command:
//
//	mockgen -source db/db.go -destination mocks/db.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks
