// Code generated by MockGen. DO NOT EDIT.
// Source: utils/path.go
//
// Generated by this command:
//
//	mockgen -source utils/path.go -destination mocks/path.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks
