// Code generated by MockGen. DO NOT EDIT.
// Source: utils/toast.go
//
// Generated by this command:
//
//	mockgen -source utils/toast.go -destination mocks/toast.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks
