// Code generated by MockGen. DO NOT EDIT.
// Source: db/util.go
//
// Generated by this command:
//
//	mockgen -source db/util.go -destination mocks/util.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks
