apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cycling-coach-lab.fullname" . }}
  labels:
    {{- include "cycling-coach-lab.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cycling-coach-lab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cycling-coach-lab.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cycling-coach-lab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DB_HOST
            {{- if .Values.postgresql.enabled }}
              value: {{ template "postgresql.fullname" . }}
            {{- else }}
              value: unknown
            {{- end }}
            - name: DB_USER
            {{- if .Values.postgresql.enabled }}
              value: {{ .Values.postgresql.auth.username | quote }}
            {{- else }}
              value: unknown
            {{- end }}
            - name: DB_PASSWORD
            {{- if .Values.postgresql.enabled }}
              value: {{ .Values.postgresql.auth.password | quote }}
            {{- else }}
              value: unknown
            {{- end }}
            - name: DB_NAME
            {{- if .Values.postgresql.enabled }}
              value: {{ .Values.postgresql.auth.database | quote }}
            {{- else }}
              value: unknown
            {{- end }}
            - name: DB_PORT
            {{- if .Values.postgresql.enabled }}
              value: "5432"
            {{- else }}
              value: unknown
            {{- end }}
            - name: VERSION
              value: {{ .Values.version | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
