name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-prod:
    environment:
      name: production
      url: https://ccl.newtri-science.michel.lu
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Store release_created in file
        run: echo ${{ steps.release.outputs.release_created }} > release_created.txt 
      - name: Upload release_created to artifactory
        uses: actions/upload-artifact@v4
        with:
          name: release_created
          path: release_created.txt
      - name: Checkout repository
        # these if statements ensure that a publication only occurs when a new release is created
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
      - name: Print Version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "New Version: v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
      - name: Build and push docker image
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/build-push-docker-image
        with:
          tag: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          isLatest: 'true'
      - name: Deploy production app
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/deploy-app
        with:
          name: prod
          tag: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          token: ${{ secrets.GH_PAT }}
          tlsName: cycling-coach-lab-tls
          subDomain: ccl
          persistence: true
      - name: Wait for review app deployment
        if: ${{ steps.release.outputs.release_created }}
        run: |
          .ci/wait_for_version_change.sh ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} "https://ccl.newtri-science.michel.lu"

